<?php
/**
 * ╔╗╔╗╔╦══╦══╦══╦════╦═══╗╔══╦═══╦═══╗
 * ║║║║║╠═╗║╔═╩╗╔╩═╗╔═╣╔══╝║╔╗║╔═╗║╔══╝
 * ║║║║║╠═╝║╚═╗║║──║║─║╚══╗║║║║╚═╝║║╔═╗
 * ║║║║║╠═╗╠═╗║║║──║║─║╔══╝║║║║╔╗╔╣║╚╗║
 * ║╚╝╚╝╠═╝╠═╝╠╝╚╗─║║─║╚══╦╣╚╝║║║║║╚═╝║
 * ╚═╝╚═╩══╩══╩══╝─╚╝─╚═══╩╩══╩╝╚╝╚═══╝
 * 
 * Examples and documentation at the: http://w3site.org
 * 
 * @copyright   Copyright (c) 2015-2016 Tereta Alexander. (http://www.w3site.org)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div class="w3site-gallery">
    <h1><?php echo $block->getTitle() ?></h1>
    <p><?php echo $block->getDescription() ?></p>
    <?php if ($block->getItems()) : ?>
        <div class="list">
            <?php foreach ($block->getItems() as $itemModel) : ?>
                <div class="list-item">
                    <?php if ($itemModel->getImage()) : ?>
                        <img src="<?php echo $itemModel->getImage() ?>"
                            alt="<?php echo $itemModel->getTitle() ?>" />
                    <?php endif ?>
                    <div class="title"><?php echo $itemModel->getTitle() ?></div>
                    <div class="description"><?php echo $itemModel->getDescription() ?></div>
                </div>
            <?php endforeach ?>
        </div>
    <?php endif ?>
</div>