<div class="w3site-gallery">
    <h1><?php echo $block->getTitle() ?></h1>
    <p><?php echo $block->getDescription() ?></p>
    <?php if ($block->getItems()) : ?>
        <div class="list">
            <?php foreach ($block->getItems() as $itemModel) : ?>
                <div class="list-item">
                    <?php if ($itemModel->getImage()) : ?>
                        <img src="<?php echo $itemModel->getImage() ?>"
                            alt="<?php echo $itemModel->getTitle() ?>" />
                    <?php endif ?>
                    <div class="title"><?php echo $itemModel->getTitle() ?></div>
                    <div class="description"><?php echo $itemModel->getDescription() ?></div>
                </div>
            <?php endforeach ?>
        </div>
    <?php endif ?>
</div>